package com.sandipan.algorithms.geeksforgeeks.arrays.hard;

import java.util.ArrayList;
import java.util.List;
import java.util.Scanner;

public class Return2PrimeNos {

	public static boolean isPrime(int n) {
		boolean[] primes = { false, false, true, true, false, true, false, true, false, false, false, true, false, true,
				false, false, false, true, false, true, false, false, false, true, false, false, false, false, false,
				true, false, true, false, false, false, false, false, true, false, false, false, true, false, true,
				false, false, false, true, false, false, false, false, false, true, false, false, false, false, false,
				true, false, true, false, false, false, false, false, true, false, false, false, true, false, true,
				false, false, false, false, false, true, false, false, false, true, false, false, false, false, false,
				true, false, false, false, false, false, false, false, true, false, false, false, true, false, true,
				false, false, false, true, false, true, false, false, false, true, false, false, false, false, false,
				false, false, false, false, false, false, false, false, true, false, false, false, true, false, false,
				false, false, false, true, false, true, false, false, false, false, false, false, false, false, false,
				true, false, true, false, false, false, false, false, true, false, false, false, false, false, true,
				false, false, false, true, false, false, false, false, false, true, false, false, false, false, false,
				true, false, true, false, false, false, false, false, false, false, false, false, true, false, true,
				false, false, false, true, false, true, false, false, false, false, false, false, false, false, false,
				false, false, true, false, false, false, false, false, false, false, false, false, false, false, true,
				false, false, false, true, false, true, false, false, false, true, false, false, false, false, false,
				true, false, true, false, false, false, false, false, false, false, false, false, true, false, false,
				false, false, false, true, false, false, false, false, false, true, false, false, false, false, false,
				true, false, true, false, false, false, false, false, true, false, false, false, true, false, true,
				false, false, false, false, false, false, false, false, false, true, false, false, false, false, false,
				false, false, false, false, false, false, false, false, true, false, false, false, true, false, true,
				false, false, false, true, false, false, false, false, false, false, false, false, false, false, false,
				false, false, true, false, false, false, false, false, true, false, false, false, false, false, false,
				false, false, false, true, false, true, false, false, false, true, false, false, false, false, false,
				true, false, false, false, false, false, false, false, true, false, false, false, false, false, true,
				false, false, false, false, false, true, false, false, false, true, false, false, false, false, false,
				true, false, false, false, false, false, false, false, true, false, false, false, true, false, false,
				false, false, false, false, false, true, false, false, false, false, false, false, false, false, false,
				true, false, true, false, false, false, false, false, false, false, false, false, true, false, true,
				false, false, false, false, false, true, false, false, false, true, false, false, false, false, false,
				true, false, false, false, false, false, false, false, true, false, false, false, true, false, true,
				false, false, false, true, false, false, false, false, false, false, false, false, false, false, false,
				true, false, false, false, false, false, false, false, true, false, false, false, true, false, false,
				false, false, false, false, false, true, false, false, false, true, false, false, false, false, false,
				true, false, false, false, false, false, false, false, false, false, false, false, true, false, true,
				false, false, false, false, false, false, false, false, false, false, false, false, false, false, false,
				false, false, true, false, false, false, false, false, true, false, false, false, false, false, false,
				false, false, false, true, false, false, false, false, false, true, false, false, false, false, false,
				true, false, true, false, false, false, false, false, true, false, false, false, false, false, false,
				false, false, false, true, false, false, false, false, false, true, false, false, false, false, false,
				true, false, true, false, false, false, false, false, true, false, false, false, false, false, true,
				false, false, false, true, false, true, false, false, false, false, false, false, false, false, false,
				false, false, true, false, false, false, false, false, false, false, false, false, true, false, true,
				false, false, false, true, false, false, false, false, false, true, false, false, false, false, false,
				true, false, true, false, false, false, false, false, false, false, false, false, false, false, true,
				false, false, false, true, false, false, false, false, false, true, false, false, false, false, false,
				false, false, true, false, false, false, false, false, false, false, false, false, true, false, false,
				false, false, false, false, false, true, false, false, false, false, false, false, false, false, false,
				true, false, false, false, false, false, false, false, true, false, false, false, false, false, true,
				false, false, false, false, false, true, false, false, false, true, false, false, false, false, false,
				false, false, true, false, false, false, false, false, true, false, false, false, true, false, false,
				false, false, false, false, false, true, false, false, false, true, false, false, false, false, false,
				false, false, false, false, false, false, false, false, true, false, false, false, false, false, false,
				false, false, false, true, false, false, false, false, false, false, false, false, false, false, false,
				true, false, true, false, false, false, false, false, false, false, false, false, true, false, true,
				false, false, false, true, false, true, false, false, false, false, false, false, false, false, false,
				true, false, false, false, false, false, false, false, false, false, false, false, false, false, true,
				false, false, false, true, false, true, false, false, false, true, false, false, false, false, false,
				false, false, false, false, false, false, false, false, true, false, false, false, true, false, true,
				false, false, false, true, false, false, false, false, false, false, false, false, false, false, false,
				false, false, false, false, false, false, false, false, true, false, false, false, true, false, false,
				false, false, false, false, false, true, false, false, false, false, false, false, false, false, false,
				true, false, false, false, false, false, false, false, true, false, false, false, true, false, false,
				false, false, false, true, false, false, false, false, false, true, false, false, false, false, false,
				false, false, false, false, false, false, false, false, true, false, false, false, true, false, false,
				false, false, false, true, false, false, false, false, false, true, false, false, false, false, false,
				false, false, true, false, false, false, false, false, true, false, false, false, false, false, false,
				false, false, false, false, false, true, false, false, false, true, false, false, false, false, false,
				true, false, true, false, false, false, false, false, false, false, false, false, true, false, true,
				false, false, false, false, false, true, false, false, false, false, false, false, false, false, false,
				true, false, true, false, false, false, false, false, false, false, false, false, true, false, true,
				false, false, false, false, false, true, false, false, false, false, false, false, false, false, false,
				false, false, false, false, false, false, false, false, true, false, false, false, true, false, true,
				false, false, false, true, false, false, false, false, false, true, false, false, false, false, false,
				true, false, false, false, false, false, false, false, true, false, false, false, false, false, true,
				false, false, false, false, false, true, false, false, false, false, false, false, false, false, false,
				false, false, false, false, false, false, false, false, false, false, false, false, true, false, true,
				false, false, false, false, false, false, false, false, false, true, false, false, false, false, false,
				false, false, true, false, false, false, false, false, false, false, false, false, true, false, false,
				false, false, false, true, false, false, false, false, false, true, false, false, false, false, false,
				false, false, true, false, false, false, false, false, false, false, false, false, false, false, true,
				false, false, false, true, false, false, false, false, false, true, false, false, false, false, false,
				true, false, true, false, false, false, false, false, true, false, false, false, false, false, false,
				false, false, false, false, false, true, false, false, false, false, false, false, false, false, false,
				true, false, false, false, false, false, false, false, false, false, false, false, false, false, false,
				false, false, false, true, false, true, false, false, false, true, false, false, false, false, false,
				true, false, true, false, false, false, false, false, true, false, false, false, true, false, true,
				false, false, false, true, false, false, false, false, false, false, false, false, false, false, false,
				true, false, true, false, false, false, false, false, true, false, false, false, false, false, false,
				false, false, false, false, false, false, false, false, false, false, false, false, false, false, false,
				false, false, false, false, false, false, false, false, false, false, false, false, true, false, false,
				false, false, false, true, false, false, false, false, false, true, false, false, false, false, false,
				false, false, true, false, false, false, false, false, false, false, false, false, false, false, false,
				false, false, false, false, false, true, false, false, false, false, false, false, false, false, false,
				true, false, false, false, false, false, false, false, false, false, false, false, false, false, true,
				false, false, false, true, false, true, false, false, false, true, false, false, false, false, false,
				true, false, false, false, false, false, false, false, true, false, false, false, true, false, true,
				false, false, false, false, false, true, false, false, false, false, false, false, false, false, false,
				false, false, true, false, false, false, false, false, false, false, false, false, true, false, true,
				false, false, false, true, false, true, false, false, false, true, false, false, false, false, false,
				true, false, false, false, false, false, false, false, false, false, false, false, true, false, false,
				false, false, false, false, false, false, false, false, false, true, false, false, false, false, false,
				false, false, true, false, false, false, false, false, false, false, false, false, false, false, true,
				false, false, false, false, false, true, false, false, false, true, false, false, false, false, false,
				true, false, false, false, false, false, false, false, true, false, false, false, true, false, false,
				false, false, false, false, false, true, false, false, false, true, false, false, false, false, false,
				false, false, false, false, false, false, false, false, true, false, false, false, true, false, false,
				false, false, false, true, false, true, false, false, false, true, false, false, false, false, false,
				true, false, true, false, false, false, false, false, true, false, false, false, false, false, false,
				false, false, false, true, false, false, false, false, false, false, false, false, false, false, false,
				false, false, false, false, false, false, false, false, true, false, false, false, false, false, true,
				false, false, false, true, false, true, false, false, false, false, false, false, false, false, false,
				false, false, false, false, false, false, false, false, false, false, false, false, false, false, true,
				false, false, false, true, false, true, false, false, false, false, false, false, false, false, false,
				true, false, false, false, false, false, false, false, false, false, false, false, true, false, true,
				false, false, false, false, false, false, false, false, false, true, false, false, false, false, false,
				false, false, true, false, false, false, false, false, true, false, false, false, false, false, true,
				false, false, false, false, false, true, false, false, false, false, false, false, false, false, false,
				false, false, false, false, false, false, false, false, true, false, false, false, false, false, true,
				false, false, false, true, false, true, false, false, false, false, false, false, false, false, false,
				false, false, true, false, false, false, false, false, false, false, false, false, true, false, false,
				false, false, false, false, false, false, false, false, false, true, false, false, false, false, false,
				false, false, true, false, false, false, false, false, false, false, false, false, false, false, false,
				false, false, false, true, false, false, false, false, false, false, false, false, false, false, false,
				false, false, true, false, false, false, false, false, true, false, false, false, true, false, true,
				false, false, false, true, false, true, false, false, false, false, false, false, false, false, false,
				true, false, false, false, false, false, false, false, false, false, false, false, true, false, false,
				false, false, false, true, false, false, false, false, false, true, false, false, false, false, false,
				false, false, false, false, false, false, false, false, false, false, false, false, true, false, true,
				false, false, false, false, false, false, false, false, false, false, false, false, false, false, false,
				true, false, true, false, false, false, false, false, false, false, false, false, false, false, false,
				false, false, false, false, false, false, false, false, false, true, false, false, false, false, false,
				true, false, false, false, false, false, false, false, true, false, false, false, false, false, true,
				false, false, false, true, false, true, false, false, false, true, false, false, false, false, false,
				false, false, true, false, false, false, false, false, true, false, false, false, false, false, false,
				false, false, false, true, false, true, false, false, false, false, false, false, false, false, false,
				true, false, false, false, false, false, false, false, false, false, false, false, false, false, true,
				false, false, false, false, false, false, false, false, false, true, false, false, false, false, false,
				true, false, false, false, false, false, false, false, false, false, false, false, true, false, true,
				false, false, false, true, false, true, false, false, false, false, false, false, false, false, false,
				true, false, false, false, false, false, false, false, false, false, false, false, true, false, true,
				false, false, false, false, false, false, false, false, false, false, false, false, false, false, false,
				true, false, true, false, false, false, false, false, true, false, false, false, true, false, true,
				false, false, false, false, false, false, false, false, false, true, false, false, false, false, false,
				false, false, true, false, false, false, false, false, false, false, false, false, false, false, false,
				false, false, false, false, false, true, false, false, false, false, false, false, false, false, false,
				false, false, false, false, false, false, false, false, false, false, false, false, false, false, true,
				false, false, false, true, false, false, false, false, false, true, false, false, false, false, false,
				false, false, true, false, false, false, false, false, false, false, false, false, false, false, false,
				false, false, false, true, false, true, false, false, false, true, false, false, false, false, false,
				false, false, true, false, false, false, false, false, false, false, false, false, false, false, false,
				false, false, false, true, false, true, false, false, false, true, false, false, false, false, false,
				false, false, true, false, false, false, false, false, true, false, false, false, false, false, true,
				false, false, false, true, false, false, false, false, false, false, false, false, false, false, false,
				true, false, true, false, false, false, false, false, false, false, false, false, false, false, false,
				false, false, false, false, false, false, false, false, false, true, false, false, false, false, false,
				true, false, true, false, false, false, false, false, true, false, false, false, true, false, false,
				false, false, false, true, false, false, false, false, false, false, false, false, false, false, false,
				false, false, true, false, false, false, false, false, true, false, false, false, true, false, true,
				false, false, false, false, false, true, false, false, false, true, false, false, false, false, false,
				true, false, false, false, false, false, false, false, false, false, false, false, true, false, false,
				false, false, false, true, false, false, false, false, false, true, false, false, false, false, false,
				false, false, false, false, false, false, false, false, true, false, false, false, true, false, false,
				false, false, false, true, false, false, false, false, false, false, false, false, false, false, false,
				true, false, false, false, false, false, false, false, true, false, false, false, false, false, true,
				false, false, false, true, false, false, false, false, false, false, false, false, false, false, false,
				false, false, false, false, false, false, false, false, false, false, false, false, false, false, true,
				false, false, false, false, false, false, false, false, false, false, false, false, false, false, false,
				false, false, true, false, false, false, false, false, false, false, false, false, true, false, false,
				false, false, false, false, false, true, false, false, false, true, false, false, false, false, false,
				true, false, true, false, false, false, false, false, true, false, false, false, false, false, false,
				false, false, false, false, false, false, false, false, false, false, false, false, false, false, false,
				true, false, false, false, false, false, false, false, false, false, false, false, true, false, true,
				false, false, false, false, false, false, false, false, false, false, false, false, false, false, false,
				true, false, false, false, false, false, false, false, true, false, false, false, true, false, false,
				false, false, false, false, false, false, false, false, false, true, false, false, false, false, false,
				false, false, false, false, false, false, false, false, true, false, false, false, false, false, false,
				false, false, false, true, false, true, false, false, false, true, false, false, false, false, false,
				false, false, true, false, false, false, false, false, true, false, false, false, false, false, true,
				false, false, false, true, false, true, false, false, false, true, false, false, false, false, false,
				true, false, false, false, false, false, false, false, true, false, false, false, true, false, true,
				false, false, false, false, false, true, false, false, false, false, false, false, false, false, false,
				true, false, true, false, false, false, false, false, false, false, false, false, true, false, false,
				false, false, false, false, false, true, false, false, false, true, false, false, false, false, false,
				false, false, false, false, false, false, false, false, true, false, false, false, false, false, false,
				false, false, false, true, false, false, false, false, false, false, false, false, false, false, false,
				true, false, true, false, false, false, false, false, true, false, false, false, true, false, true,
				false, false, false, false, false, false, false, false, false, false, false, false, false, false, false,
				true, false, false, false, false, false, false, false, false, false, false, false, false, false, true,
				false, false, false, true, false, false, false, false, false, true, false, false, false, false, false,
				false, false, true, false, false, false, false, false, true, false, false, false, true, false, false,
				false, false, false, false, false, false, false, false, false, false, false, false, false, false, false,
				true, false, false, false, false, false, false, false, true, false, false, false, false, false, false,
				false, false, false, true, false, false, false, false, false, true, false, false, false, false, false,
				true, false, false, false, false, false, false, false, true, false, false, false, false, false, false,
				false, false, false, true, false, false, false, false, false, false, false, false, false, false, false,
				true, false, false, false, false, false, false, false, false, false, false, false, false, false, true,
				false, false, false, true, false, false, false, false, false, true, false, false, false, false, false,
				true, false, true, false, false, false, false, false, false, false, false, false, false, false, false,
				false, false, false, false, false, false, false, false, false, false, false, false, false, false, false,
				true, false, true, false, false, false, false, false, false, false, false, false, true, false, false,
				false, false, false, false, false, true, false, false, false, true, false, false, false, false, false,
				false, false, false, false, false, false, false, false, true, false, false, false, true, false, false,
				false, false, false, false, false, true, false, false, false, false, false, false, false, false, false,
				false, false, true, false, false, false, false, false, true, false, false, false, false, false, false,
				false, false, false, false, false, true, false, false, false, true, false, false, false, false, false,
				true, false, false, false, false, false, false, false, false, false, false, false, false, false, false,
				false, false, false, false, false, true, false, false, false, false, false, false, false, false, false,
				true, false, true, false, false, false, false, false, false, false, false, false, false, false, false,
				false, false, false, true, false, false, false, false, false, false, false, false, false, false, false,
				false, false, false, false, false, false, false, false, false, false, false, false, false, false, true,
				false, false, false, true, false, true, false, false, false, false, false, false, false, false, false,
				false, false, true, false, false, false, false, false, true, false, false, false, true, false, false,
				false, false, false, false, false, false, false, false, false, true, false, false, false, false, false,
				true, false, false, false, false, false, false, false, true, false, false, false, true, false, false,
				false, false, false, false, false, true, false, false, false, false, false, false, false, false, false,
				false, false, false, false, false, false, false, false, false, false, false, false, true, false, true,
				false, false, false, true, false, true, false, false, false, false, false, false, false, false, false,
				false, false, true, false, false, false, false, false, false, false, false, false, false, false, false,
				false, false, false, false, false, false, false, false, false, false, false, false, false, false, false,
				true, false, true, false, false, false, false, false, true, false, false, false, false, false, true,
				false, false, false, false, false, true, false, false, false, true, false, false, false, false, false,
				true, false, true, false, false, false, false, false, false, false, false, false, false, false, true,
				false, false, false, true, false, false, false, false, false, false, false, false, false, false, false,
				true, false, true, false, false, false, false, false, false, false, false, false, true, false, true,
				false, false, false, false, false, false, false, false, false, false, false, false, false, false, false,
				true, false, true, false, false, false, false, false, false, false, false, false, false, false, false,
				false, false, false, true, false, false, false, false, false, true, false, false, false, false, false,
				false, false, false, false, false, false, false, false, false, false, false, false, false, false, true,
				false, false, false, false, false, false, false, false, false, false, false, false, false, false, false,
				true, false, false, false, false, false, false, false, true, false, false, false, true, false, true,
				false, false, false, true, false, true, false, false, false, false, false, false, false, false, false,
				false, false, false, false, false, false, false, false, false, false, false, false, true, false, false,
				false, false, false, false, false, true, false, false, false, false, false, false, false, false, false,
				false, false, true, false, false, false, false, false, true, false, false, false, false, false, false,
				false, false, false, true, false, true, false, false, false, true, false, false, false, false, false,
				true, false, true, false, false, false, false, false, true, false, false, false, false, false, false,
				false, false, false, true, false, true, false, false, false, false, false, false, false, false, false,
				false, false, true, false, false, false, false, false, false, false, false, false, true, false, true,
				false, false, false, false, false, false, false, false, false, true, false, false, false, false, false,
				false, false, false, false, false, false, false, false, true, false, false, false, false, false, true,
				false, false, false, true, false, false, false, false, false, true, false, false, false, false, false,
				false, false, true, false, false, false, false, false, true, false, false, false, false, false, true,
				false, false, false, false, false, false, false, false, false, false, false, false, false, false, false,
				true, false, false, false, false, false, false, false, false, false, false, false, true, false, true,
				false, false, false, true, false, false, false, false, false, false, false, false, false, false, false,
				false, false, true, false, false, false, false, false, true, false, false, false, true, false, false,
				false, false, false, false, false, true, false, false, false, false, false, false, false, false, false,
				true, false, false, false, false, false, false, false, true, false, false, false, false, false, true,
				false, false, false, false, false, true, false, false, false, false, false, false, false, false, false,
				false, false, false, false, false, false, false, false, false, false, false, false, true, false, false,
				false, false, false, true, false, true, false, false, false, false, false, false, false, false, false,
				true, false, false, false, false, false, false, false, false, false, false, false, false, false, true,
				false, false, false, true, false, false, false, false, false, true, false, false, false, false, false,
				false, false, false, false, false, false, false, false, false, false, false, false, true, false, true,
				false, false, false, false, false, false, false, false, false, true, false, false, false, false, false,
				false, false, false, false, false, false, false, false, true, false, false, false, true, false, true,
				false, false, false, false, false, false, false, false, false, true, false, false, false, false, false,
				false, false, false, false, false, false, false, false, true, false, false, false, true, false, false,
				false, false, false, false, false, true, false, false, false, false, false, false, false, false, false,
				false, false, false, false, false, false, false, false, true, false, false, false, true, false, false,
				false, false, false, true, false, true, false, false, false, true, false, false, false, false, false,
				true, false, true, false, false, false, false, false, false, false, false, false, false, false, true,
				false, false, false, true, false, false, false, false, false, false, false, false, false, false, false,
				false, false, false, false, false, false, false, false, true, false, false, false, false, false, false,
				false, false, false, false, false, false, false, false, false, false, false, false, false, false, false,
				true, false, false, false, false, false, false, false, false, false, false, false, true, false, true,
				false, false, false, true, false, false, false, false, false, true, false, false, false, false, false,
				true, false, true, false, false, false, false, false, true, false, false, false, false, false, false,
				false, false, false, false, false, false, false, false, false, false, false, false, false, false, false,
				true, false, true, false, false, false, false, false, true, false, false, false, false, false, false,
				false, false, false, false, false, false, false, false, false, true, false, false, false, false, false,
				true, false, false, false, false, false, false, false, false, false, false, false, true, false, true,
				false, false, false, false, false, true, false, false, false, false, false, false, false, false, false,
				false, false, true, false, false, false, false, false, false, false, false, false, false, false, false,
				false, false, false, true, false, true, false, false, false, true, false, false, false, false, false,
				true, false, false, false, false, false, false, false, false, false, false, false, false, false, true,
				false, false, false, true, false, true, false, false, false, false, false, false, false, false, false,
				false, false, false, false, false, false, false, false, true, false, false, false, false, false, false,
				false, false, false, false, false, false, false, false, false, false, false, false, false, false, false,
				false, false, true, false, false, false, false, false, false, false, false, false, true, false, false,
				false, false, false, true, false, true, false, false, false, false, false, false, false, false, false,
				true, false, true, false, false, false, false, false, false, false, false, false, true, false, true,
				false, false, false, false, false, false, false, false, false, true, false, false, false, false, false,
				true, false, true, false, false, false, false, false, false, false, false, false, true, false, true,
				false, false, false, false, false, false, false, false, false, true, false, false, false, false, false,
				true, false, false, false, false, false, false, false, true, false, false, false, false, false, false,
				false, false, false, false, false, false, false, false, false, false, false, false, false, false, false,
				false, false, false, false, false, false, false, false, true, false, false, false, false, false, false,
				false, false, false, true, false, true, false, false, false, false, false, false, false, false, false,
				true, false, false, false, false, false, false, false, true, false, false, false, false, false, true,
				false, false, false, false, false, false, false, false, false, true, false, false, false, false, false,
				false, false, false, false, false, false, false, false, false, false, false, false, true, false, false,
				false, false, false, true, false, false, false, false, false, false, false, false, false, false, false,
				true, false, false, false, false, false, false, false, false, false, false, false, true, false, true,
				false, false, false, false, false, false, false, false, false, false, false, false, false, false, false,
				false, false, true, false, false, false, false, false, true, false, false, false, true, false, false,
				false, false, false, true, false, false, false, false, false, true, false, false, false, false, false,
				false, false, false, false, false, false, false, false, false, false, false, false, true, false, true,
				false, false, false, false, false, false, false, false, false, true, false, false, false, false, false,
				false, false, false, false, false, false, false, false, true, false, false, false, false, false, true,
				false, false, false, true, false, true, false, false, false, true, false, false, false, false, false,
				false, false, false, false, false, false, false, false, false, false, false, false, false, false, false,
				false, false, false, true, false, true, false, false, false, false, false, false, false, false, false,
				false, false, true, false, false, false, false, false, true, false, false, false, false, false, false,
				false, false, false, false, false, false, false, false, false, true, false, false, false, false, false,
				false, false, true, false, false, false, false, false, true, false, false, false, false, false, true,
				false, false, false, false, false, false, false, false, false, false, false, false, false, false, false,
				false, false, true, false, false, false, false, false, false, false, false, false, false, false, false,
				false, false, false, true, false, true, false, false, false, true, false, false, false, false, false,
				true, false, true, false, false, false, false, false, true, false, false, false, false, false, true,
				false, false, false, false, false, false, false, false, false, true, false, false, false, false, false,
				true, false, false, false, false, false, false, false, false, false, false, false, true, false, false,
				false, false, false, false, false, false, false, false, false, true, false, false, false, false, false,
				false, false, false, false, false, false, false, false, false, false, false, false, true, false, true,
				false, false, false, false, false, true, false, false, false, true, false, false, false, false, false,
				false, false, false, false, false, false, false, false, false, false, false, false, true, false, false,
				false, false, false, false, false, true, false, false, false, false, false, false, false, false, false,
				false, false, false, false, false, false, false, false, false, false, false, false, false, false, true,
				false, false, false, true, false, true, false, false, false, true, false, false, false, false, false,
				true, false, true, false, false, false, false, false, false, false, false, false, false, false, true,
				false, false, false, true, false, false, false, false, false, false, false, false, false, false, false,
				false, false, true, false, false, false, false, false, false, false, false, false, false, false, false,
				false, false, false, false, false, false, false, false, false, false, false, false, false, false, false,
				false, false, true, false, false, false, false, false, false, false, false, false, true, false, false,
				false, false, false, true, false, false, false, false, false, false, false, false, false, false, false,
				true, false, false, false, false, false, false, false, false, false, false, false, false, false, true,
				false, false, false, false, false, true, false, false, false, false, false, false, false, false, false,
				true, false, false, false, false, false, false, false, false, false, false, false, true, false, true,
				false, false, false, true, false, false, false, false, false, true, false, false, false, false, false,
				false, false, true, false, false, false, false, false, true, false, false, false, false, false, false,
				false, false, false, true, false, true, false, false, false, true, false, false, false, false, false,
				false, false, false, false, false, false, false, false, true, false, false, false, false, false, true,
				false, false, false, false, false, true, false, false, false, true, false, false, false, false, false,
				true, false, true, false, false, false, false, false, false, false, false, false, true, false, true,
				false, false, false, false, false, false, false, false, false, false, false, false, false, false, false,
				true, false, false, false, false, false, false, false, false, false, false, false, true, false, false,
				false, false, false, false, false, true, false, false, false, false, false, false, false, false, false,
				false, false, false, false, false, false, false, false, true, false, false, false, true, false, false,
				false, false, false, true, false, false, false, false, false, false, false, false, false, false, false,
				true, false, true, false, false, false, false, false, true, false, false, false, false, false, true,
				false, false, false, false, false, true, false, false, false, false, false, false, false, false, false,
				false, false, false, false, false, false, false, false, false, false, false, false, false, false, false,
				false, false, false, true, false, false, false, false, false, true, false, false, false, false, false,
				false, false, false, false, false, false, false, false, true, false, false, false, true, false, false,
				false, false, false, false, false, true, false, false, false, false, false, false, false, false, false,
				true, false, false, false, false, false, false, false, true, false, false, false, false, false, false,
				false, false, false, false, false, true, false, false, false, false, false, false, false, false, false,
				false, false, false, false, false, false, false, false, true, false, false, false, true, false, true,
				false, false, false, true, false, false, false, false, false, false, false, false, false, false, false,
				false, false, false, false, false, false, false, false, false, false, false, false, true, false, false,
				false, false, false, false, false, false, false, false, false, true, false, false, false, false, false,
				true, false, true, false, false, false, false, false, false, false, false, false, false, false, false,
				false, false, false, true, false, false, false, false, false, true, false, false, false, false, false,
				true, false, false, false, false, false, false, false, false, false, false, false, false, false, true,
				false, false, false, false, false, false, false, false, false, true, false, false, false, false, false,
				false, false, false, false, false, false, false, false, true, false, false, false, true, false, false,
				false, false, false, false, false, false, false, false, false, false, false, false, false, false, false,
				false, false, false, false, false, false, false, false, false, false, false, false, true, false, false,
				false, false, false, true, false, false, false, false, false, true, false, false, false, false, false,
				true, false, false, false, false, false, false, false, true, false, false, false, false, false, true,
				false, false, false, true, false, true, false, false, false, false, false, false, false, false, false,
				false, false, true, false, false, false, false, false, true, false, false, false, true, false, true,
				false, false, false, false, false, true, false, false, false, false, false, false, false, false, false,
				false, false, false, false, false, false, false, false, false, false, false, false, true, false, false,
				false, false, false, true, false, true, false, false, false, true, false, false, false, false, false,
				false, false, false, false, false, false, false, false, false, false, false, false, true, false, true,
				false, false, false, true, false, false, false, false, false, false, false, false, false, false, false,
				true, false, true, false, false, false, false, false, true, false, false, false, true, false, false,
				false, false, false, false, false, false, false, false, false, false, false, false, false, false, false,
				false, false, false, false, false, false, false, false, true, false, false, false, false, false, true,
				false, false, false, false, false, true, false, false, false, true, false, false, false, false, false,
				false, false, true, false, false, false, false, false, false, false, false, false, true, false, false,
				false, false, false, false, false, false, false, false, false, false, false, false, false, false, false,
				false, false, false, false, false, false, false, false, false, false, false, false, false, false, true,
				false, false, false, false, false, false, false, false, false, false, false, false, false, false, false,
				true, false, true, false, false, false, false, false, true, false, false, false, true, false, true,
				false, false, false, true, false, true, false, false, false, false, false, false, false, false, false,
				true, false, false, false, false, false, false, false, false, false, false, false, false, false, true,
				false, false, false, false, false, true, false, false, false, true, false, false, false, false, false,
				false, false, true, false, false, false, false, false, false, false, false, false, true, false, false,
				false, false, false, true, false, false, false, false, false, false, false, false, false, false, false,
				false, false, false, false, false, false, false, false, true, false, false, false, true, false, true,
				false, false, false, false, false, true, false, false, false, false, false, false, false, false, false,
				false, false, false, false, false, false, false, false, false, false, false, false, false, false, false,
				false, false, false, false, false, true, false, false, false, true, false, false, false, false, false,
				false, false, true, false, false, false, false, false, false, false, false, false, true, false, false,
				false, false, false, true, false, false, false, false, false, true, false, false, false, false, false,
				false, false, true, false, false, false, false, false, true, false, false, false, false, false, false,
				false, false, false, false, false, true, false, false, false, true, false, false, false, false, false,
				true, false, true, false, false, false, false, false, true, false, false, false, true, false, false,
				false, false, false, true, false, true, false, false, false, false, false, false, false, false, false,
				true, false, true, false, false, false, false, false, false, false, false, false, false, false, false,
				false, false, false, true, false, false, false, false, false, true, false, false, false, false, false,
				false, false, false, false, false, false, false, false, false, false, false, false, false, false, true,
				false, false, false, true, false, false, false, false, false, false, false, false, false, false, false,
				true, false, false, false, false, false, false, false, false, false, false, false, false, false, true,
				false, false, false, false, false, false, false, false, false, false, false, false, false, false, false,
				false, false, false, false, false, false, false, false, false, false, false, false, true, false, false,
				false, false, false, true, false, false, false, false, false, false, false, false, false, false, false,
				false, false, false, false, false, false, false, false, true, false, false, false, true, false, false,
				false, false, false, false, false, false, false, false, false, false, false, false, false, false, false,
				true, false, false, false, false, false, false, false, true, false, false, false, false, false, true,
				false, false, false, true, false, false, false, false, false, true, false, false, false, false, false,
				false, false, false, false, false, false, false, false, true, false, false, false, false, false, true,
				false, false, false, false, false, true, false, false, false, false, false, false, false, false, false,
				true, false, true, false, false, false, false, false, false, false, false, false, true, false, false,
				false, false, false, false, false, false, false, false, false, true, false, false, false, false, false,
				false, false, true, false, false, false, false, false, false, false, false, false, true, false, true,
				false, false, false, false, false, false, false, false, false, true, false, false, false, false, false,
				false, false, true, false, false, false, false, false, false, false, false, false, false, false, true,
				false, false, false, false, false, false, false, false, false, true, false, false, false, false, false,
				false, false, false, false, false, false, false, false, false, false, false, false, false, false, false,
				false, false, false, true, false, true, false, false, false, true, false, false, false, false, false,
				false, false, true, false, false, false, false, false, true, false, false, false, true, false, false,
				false, false, false, false, false, true, false, false, false, false, false, false, false, false, false,
				false, false, false, false, false, false, false, false, true, false, false, false, false, false, false,
				false, false, false, true, false, false, false, false, false, true, false, false, false, false, false,
				true, false, true, false, false, false, false, false, true, false, false, false, false, false, false,
				false, false, false, true, false, false, false, false, false, false, false, false, false, false, false,
				true, false, true, false, false, false, false, false, false, false, false, false, true, false, false,
				false, false, false, true, false, false, false, false, false, true, false, false, false, false, false,
				true, false, false, false, false, false, false, false, true, false, false, false, false, false, true,
				false, false, false, false, false, false, false, false, false, true, false, false, false, false, false,
				true, false, true, false, false, false, false, false, true, false, false, false, false, false, true,
				false, false, false, false, false, true, false, false, false, false, false, false, false, false, false,
				true, false, false, false, false, false, false, false, true, false, false, false, false, false, false,
				false, false, false, false, false, false, false, false, false, false, false, false, false, false, false,
				false, false, true, false, false, false, false, false, true, false, false, false, false, false, false,
				false, false, false, false, false, false, false, false, false, false, false, false, false, false, false,
				true, false, true, false, false, false, false, false, false, false, false, false, false, false, false,
				false, false, false, false, false, true, false, false, false, true, false, false, false, false, false,
				false, false, true, false, false, false, false, false, false, false, false, false, true, false, false,
				false, false, false, false, false, false, false, false, false, false, false, false, false, false, false,
				false, false, false, false, false, false, false, false, false, false, false, false, true, false, false,
				false, false, false, false, false, true, false, false, false, false, false, false, false, false, false,
				false, false, false, false, false, false, false, false, true, false, false, false, true, false, true,
				false, false, false, false, false, false, false, false, false, true, false, false, false, false, false,
				true, false, true, false, false, false, false, false, true, false, false, false, true, false, false,
				false, false, false, false, false, false, false, false, false, false, false, false, false, false, false,
				true, false, false, false, false, false, false, false, true, false, false, false, false, false, false,
				false, false, false, false, false, true, false, false, false, false, false, false, false, false, false,
				false, false, false, false, false, false, false, false, true, false, false, false, false, false, false,
				false, false, false, false, false, false, false, false, false, true, false, false, false, false, false,
				true, false, true, false, false, false, false, false, false, false, false, false, false, false, true,
				false, false, false, false, false, true, false, false, false, false, false, false, false, false, false,
				true, false, true, false, false, false, false, false, false, false, false, false, true, false, true,
				false, false, false, false, false, true, false, false, false, false, false, false, false, false, false,
				true, false, false, false, false, false, false, false, false, false, false, false, false, false, true,
				false, false, false, true, false, false, false, false, false, false, false, false, false, false, false,
				false, false, false, false, false, false, false, false, false, false, false, false, true, false, true,
				false, false, false, false, false, false, false, false, false, false, false, false, false, false, false,
				true, false, true, false, false, false, false, false, false, false, false, false, true, false, true,
				false, false, false, false, false, false, false, false, false, true, false, false, false, false, false,
				false, false, false, false, false, false, false, false, false, false, false, false, false, false, true,
				false, false, false, true, false, true, false, false, false, true, false, false, false, false, false,
				false, false, true, false, false, false, false, false, false, false, false, false, false, false, false,
				false, false, false, true, false, false, false, false, false, true, false, false, false, false, false,
				true, false, true, false, false, false, false, false, false, false, false, false, false, false, true,
				false, false, false, false, false, false, false, false, false, false, false, false, false, false, false,
				true, false, false, false, false, false, false, false, true, false, false, false, true, false, false,
				false, false, false, true, false, false, false, false, false, false, false, false, false, false, false,
				false, false, false, false, false, false, false, false, false, false, false, false, false, false, false,
				false, false, false, true, false, true, false, false, false, false, false, false, false, false, false,
				true, false, true, false, false, false, false, false, true, false, false, false, true, false, false,
				false, false, false, true, false, false, false, false, false, true, false, false, false, false, false,
				false, false, true, false, false, false, false, false, true, false, false, false, true, false, false,
				false, false, false, false, false, false, false, false, false, true, false, false, false, false, false,
				true, false, false, false, false, false, false, false, true, false, false, false, false, false, false,
				false, false, false, false, false, true, false, false, false, true, false, false, false, false, false,
				false, false, false, false, false, false, false, false, true, false, false, false, false, false, false,
				false, false, false, false, false, true, false, false, false, false, false, false, false, false, false,
				true, false, false, false, false, false, false, false, false, false, false, false, false, false, false,
				false, false, false, false, false, false, false, false, false, true, false, false, false, false, false,
				true, false, false, false, false, false, false, false, false, false, false, false, true, false, false,
				false, false, false, true, false, true, false, false, false, false, false, false, false, false, false,
				false, false, false, false, false, false, false, false, false, false, false, false, true, false, false,
				false, false, false, false, false, true, false, false, false, false, false, false, false, false, false,
				false, false, false, false, false, false, false, false, true, false, false, false, false, false, false,
				false, false, false, true, false, false, false, false, false, true, false, false, false, false, false,
				false, false, false, false, false, false, false, false, true, false, false, false, true, false, true,
				false, false, false, false, false, true, false, false, false, false, false, false, false, false, false,
				true, false, false, false, false, false, false, false, true, false, false, false, false, false, true,
				false, false, false, true, false, false, false, false, false, true, false, false, false, false, false,
				false, false, false, false, false, false, false, false, false, false, false, false, false, false, false,
				false, false, false, false, false, false, false, false, false, true, false, false, false, false, false,
				false, false, false, false, false, false, false, false, true, false, false, false, false, false, false,
				false, false, false, true, false, true, false, false, false, false, false, false, false, false, false,
				false, false, true, false, false, false, false, false, false, false, false, false, true, false, true,
				false, false, false, false, false, false, false, false, false, false, false, false, false, false, false,
				true, false, true, false, false, false, false, false, false, false, false, false, false, false, false,
				false, false, false, false, false, true, false, false, false, false, false, false, false, false, false,
				false, false, false, false, false, false, false, false, false, false, false, false, false, false, true,
				false, false, false, false, false, false, false, false, false, false, false, false, false, false, false,
				false, false, true, false, false, false, false, false, true, false, false, false, false, false, false,
				false, false, false, false, false, false, false, false, false, true, false, false, false, false, false,
				false, false, false, false, false, false, false, false, false, false, false, false, true, false, false,
				false, false, false, true, false, true, false, false, false, false, false, false, false, false, false,
				false, false, false, false, false, false, false, false, true, false, false, false, true, false, false,
				false, false, false, true, false, true, false, false, false, false, false, false, false, false, false,
				true, false, false, false, false, false, false, false, true, false, false, false, false, false, false,
				false, false, false, true, false, false, false, false, false, true, false, false, false, false, false,
				true, false, false, false, false, false, false, false, true, false, false, false, true, false, false,
				false, false, false, true, false, true, false, false, false, false, false, false, false, false, false,
				true, false, true, false, false, false, false, false, false, false, false, false, false, false, true,
				false, false, false, true, false, false, false, false, false, true, false, false, false, false, false,
				true, false, true, false, false, false, false, false, false, false, false, false, false, false, true,
				false, false, false, true, false, false, false, false, false, false, false, false, false, false, false,
				false, false, true, false, false, false, false, false, false, false, false, false, false, false, false,
				false, false, false, false, false, true, false, false, false, true, false, false, false, false, false,
				true, false, false, false, false, false, false, false, false, false, false, false, false, false, false,
				false, false, false, false, false, true, false, false, false, true, false, false, false, false, false,
				false, false, true, false, false, false, false, false, true, false, false, false, true, false, false,
				false, false, false, false, false, true, false, false, false, true, false, false, false, false, false,
				false, false, false, false, false, false, false, false, true, false, false, false, false, false, true,
				false, false, false, true, false, false, false, false, false, false, false, false, false, false, false,
				false, false, true, false, false, false, false, false, false, false, false, false, false, false, true,
				false, false, false, true, false, true, false, false, false, false, false, false, false, false, false,
				false, false, false, false, false, false, false, false, false, false, false, false, false, false, false,
				false, false, false, false, false, true, false, false, false, true, false, false, false, false, false,
				false, false, false, false, false, false, false, false, false, false, false, false, false, false, false,
				false, false, false, true, false, false, false, false, false, true, false, false, false, false, false,
				true, false, false, false, false, false, false, false, false, false, false, false, true, false, false,
				false, false, false, false, false, false, false, false, false, true, false, false, false, false, false,
				false, false, false, false, false, false, false, false, true, false, false, false, false, false, true,
				false, false, false, true, false, true, false, false, false, true, false, false, false, false, false,
				false, false, false, false, false, false, false, false, false, false, false, false, true, false, false,
				false, false, false, true, false, false, false, false, false, false, false, false, false, false, false,
				true, false, false, false, false, false, false, false, true, false, false, false, false, false, true,
				false, false, false, true, false, false, false, false, false, false, false, false, false, false, false,
				true, false, true, false, false, false, false, false, false, false, false, false, false, false, true,
				false, false, false, false, false, false, false, false, false, false, false, false, false, false, false,
				false, false, false, false, false, false, false, false, false, false, false, false, false, false, true,
				false, false, false, false, false, false, false, false, false, false, false, false, false, false, false,
				true, false, true, false, false, false, false, false, true, false, false, false, false, false, false,
				false, false, false, false, false, false, false, false, false, false, false, false, false, false, false,
				true, false, false, false, false, false, false, false, false, false, false, false, false, false, true,
				false, false, false, false, false, true, false, false, false, false, false, false, false, false, false,
				true, false, false, false, false, false, false, false, false, false, false, false, true, false, false,
				false, false, false, true, false, true, false, false, false, true, false, false, false, false, false,
				false, false, true, false, false, false, false, false, false, false, false, false, true, false, false,
				false, false, false, true, false, false, false, false, false, true, false, false, false, false, false,
				false, false, false, false, false, false, false, false, false, false, false, false, false, false, false,
				false, false, false, true, false, false, false, false, false, false, false, false, false, false, false,
				false, false, true, false, false, false, false, false, true, false, false, false, true, false, false,
				false, false, false, false, false, true, false, false, false, false, false, false, false, false, false,
				false, false, true, false, false, false, false, false, false, false, false, false, false, false, false,
				false, false, false, false, false, true, false, false, false, false, false, false, false, false, false,
				true, false, true, false, false, false, false, false, false, false, false, false, true, false, true,
				false, false, false, true, false, false, false, false, false, true, false, false, false, false, false,
				false, false, false, false, false, false, false, false, false, false, false, false, false, false, true,
				false, false, false, false, false, true, false, false, false, true, false, false, false, false, false,
				false, false, false, false, false, false, false, false, true, false, false, false, true, false, true,
				false, false, false, true, false, false, false, false, false, false, false, false, false, false, false,
				false, false, true, false, false, false, false, false, true, false, false, false, false, false, false,
				false, false, false, false, false, true, false, false, false, false, false, false, false, false, false,
				false, false, false, false, false, false, false, false, false, false, false, false, false, false, true,
				false, false, false, false, false, false, false, false, false, true, false, false, false, false, false,
				true, false, false, false, false, false, false, false, true, false, false, false, false, false, false,
				false, false, false, true, false, true, false, false, false, false, false, false, false, false, false,
				false, false, false, false, false, false, false, false, false, false, false, false, false, false, false,
				false, false, false, false, false, true, false, false, false, true, false, false, false, false, false,
				true, false, true, false, false, false, false, false, false, false, false, false, false, false, true,
				false, false, false, true, false, false, false, false, false, false, false, false, false, false, false,
				false, false, true, false, false, false, false, false, true, false, false, false, false, false, false,
				false, false, false, false, false, false, false, false, false, false, false, false, false, false, false,
				false, false, false, false, false, false, false, false, false, false, false, false, true, false, false,
				false, false, false, false, false, false, false, false, false, true, false, false, false, false, false,
				false, false, true, false, false, false, false, false, true, false, false, false, false, false, false,
				false, false, false, true, false, true, false, false, false, true, false, false, false, false, false,
				false, false, false, false, false, false, false, false, false, false, false, false, false, false, true,
				false, false, false, false, false, false, false, false, false, true, false, false, false, false, false,
				false, false, true, false, false, false, false, false, false, false, false, false, false, false, false,
				false, false, false, true, false, true, false, false, false, false, false, false, false, false, false,
				true, false, false, false, false, false, false, false, false, false, false, false, false, false, true,
				false, false, false, true, false, true, false, false, false, false, false, false, false, false, false,
				false, false, true, false, false, false, false, false, true, false, false, false, false, false, false,
				false, false, false, false, false, false, false, false, false, true, false, false, false, false, false,
				true, false, false, false, false, false, false, false, true, false, false, false, true, false, false,
				false, false, false, false, false, true, false, false, false, true, false, false, false, false, false,
				true, false, false, false, false, false, false, false, true, false, false, false, false, false, true,
				false, false, false, false, false, true, false, false, false, false, false, false, false, false, false,
				false, false, true, false, false, false, false, false, true, false, false, false, true, false, false,
				false, false, false, true, false, false, false, false, false, true, false, false, false, false, false,
				false, false, true, false, false, false, false, false, false, false, false, false, false, false, false,
				false, false, false, false, false, true, false, false, false, true, false, false, false, false, false,
				false, false, false, false, false, false, false, false, false, false, false, false, false, false, true,
				false, false, false, true, false, false, false, false, false, false, false, false, false, false, false,
				true, false, true, false, false, false, false, false, false, false, false, false, true, false, false,
				false, false, false, true, false, true, false, false, false, false, false, false, false, false, false,
				true, false, false, false, false, false, false, false, false, false, false, false, true, false, true,
				false, false, false, true, false, false, false, false, false, false, false, false, false, false, false,
				false, false, false, false, false, false, false, false, true, false, false, false, false, false, true,
				false, false, false, false, false, false, false, false, false, false, false, false, false, false, false,
				false, false, false, false, false, false, false, false, false, false, false, false, false, false, true,
				false, false, false, false, false, true, false, false, false, true, false, false, false, false, false,
				false, false, true, false, false, false, false, false, false, false, false, false, true, false, false,
				false, false, false, false, false, false, false, false, false, true, false, false, false, false, false,
				true, false, true, false, false, false, false, false, false, false, false, false, false, false, false,
				false, false, false, false, false, false, false, false, false, false, false, false, false, false, false,
				true, false, true, false, false, false, false, false, true, false, false, false, true, false, true,
				false, false, false, false, false, false, false, false, false, false, false, false, false, false, false,
				true, false, false, false, false, false, false, false, false, false, false, false, true, false, true,
				false, false, false, false, false, true, false, false, false, false, false, false, false, false, false,
				true, false, false, false, false, false, false, false, true, false, false, false, false, false, false,
				false, false, false, false, false, false, false, false, false, false, false, false, false, false, false,
				false, false, true, false, false, false, false, false, false, false, false, false, false, false, true,
				false, false, false, false, false, true, false, false, false, false, false, false, false, false, false,
				false, false, false, false, false, false, false, false, true, false, false, false, false, false, true,
				false, false, false, true, false, false, false, false, false, false, false, false, false, false, false,
				false, false, true, false, false, false, false, false, true, false, false, false, true, false, false,
				false, false, false, false, false, false, false, false, false, true, false, false, false, false, false,
				false, false, true, false, false, false, false, false, true, false, false, false, false, false, false,
				false, false, false, false, false, true, false, false, false, true, false, false, false, false, false,
				true, false, false, false, false, false, false, false, false, false, false, false, true, false, false,
				false, false, false, true, false, false, false, false, false, false, false, false, false, false, false,
				true, false, true, false, false, false, false, false, false, false, false, false, false, false, false,
				false, false, false, true, false, false, false, false, false, false, false, false, false, false, false,
				false, false, false, false, false, false, false, false, true, false, false, false, true, false, true,
				false, false, false, false, false, false, false, false, false, true, false, false, false, false, false,
				false, false, false, false, false, false, false, false, false, false, false, false, true, false, false,
				false, false, false, false, false, true, false, false, false, true, false, false, false, false, false,
				false, false, false, false, false, false, false, false, true, false, false, false, true, false, true,
				false, false, false, false, false, true, false, false, false, false, false, false, false, false, false,
				false, false, false, false, false, false, false, false, false, false, false, false, true, false, false,
				false, false, false, true, false, false, false, false, false, false, false, false, false, false, false,
				false, false, true, false, false, false, false, false, true, false, false, false, false, false, true,
				false, false, false, false, false, false, false, false, false, true, false, false, false, false, false,
				true, false, true, false, false, false, false, false, false, false, false, false, true, false, true,
				false, false, false, true, false, true, false, false, false, false, false, false, false, false, false,
				false, false, false, false, false, false, false, false, false, false, false, false, true, false, true,
				false, false, false, true, false, false, false, false, false, true, false, false, false, false, false,
				true, false, false, false, false, false, false, false, false, false, false, false, true, false, false,
				false, false, false, true, false, false, false, false, false, false, false, false, false, false, false,
				false, false, true, false, false, false, false, false, false, false, false, false, true, false, false,
				false, false, false, false, false, false, false, false, false, true, false, false, false, false, false,
				true, false, false, false, false, false, false, false, true, false, false, false, true, false, false,
				false, false, false, false, false, false, false, false, false, false, false, false, false, false, false,
				false, false, false, false, false, false, false, false, false, false, false, false, false, false, false,
				false, false, false, true, false, false, false, false, false, false, false, false, false, false, false,
				false, false, true, false, false, false, false, false, false, false, false, false, false, false, true,
				false, false, false, false, false, true, false, false, false, true, false, false, false, false, false,
				true, false, true, false, false, false, false, false, false, false, false, false, false, false, true,
				false, false, false, false, false, true, false, false, false, false, false, false, false, false, false,
				false, false, true, false, false, false, false, false, false, false, false, false, false, false, false,
				false, false, false, true, false, true, false, false, false, false, false, false, false, false, false,
				true, false, false, false, false, false, false, false, true, false, false, false, false, false, false,
				false, false, false, false, false, false, false, false, false, false, false, false, false, false, false,
				true, false, true, false, false, false, false, false, false, false, false, false, false, false, true,
				false, false, false, false, false, true, false, false, false, true, false, false, false, false, false,
				true, false, false, false, false, false, false, false, false, false, false, false, false, false, false,
				false, false, false, true, false, true, false, false, false, false, false, false, false, false, false,
				false, false, true, false, false, false, false, false, true, false, false, false, true, false, false,
				false, false, false, false, false, false, false, false, false, true, false, false, false, false, false,
				false, false, true, false, false, false, false, false, true, false, false, false, false, false, false,
				false, false, false, false, false, true, false, false, false, true, false, false, false, false, false,
				true, false, false, false, false, false, false, false, false, false, false, false, true, false, false,
				false, false, false, true, false, true, false, false, false, false, false, false, false, false, false,
				false, false, true, false, false, false, false, false, false, false, false, false, false, false, true,
				false, false, false, true, false, false, false, false, false, false, false, false, false, false, false,
				false, false, true, false, false, false, false, false, true, false, false, false, false, false, false,
				false, false, false, false, false, false, false, false, false, true, false, false, false, false, false,
				true, false, true, false, false, false, false, false, false, false, false, false, true, false, false,
				false, false, false, false, false, true, false, false, false, false, false, false, false, false, false,
				false, false, false, false, false, false, false, false, true, false, false, false, false, false, true,
				false, false, false, false, false, false, false, false, false, false, false, false, false, false, false,
				false, false, false, false, false, false, false, false, false, false, false, false };

		return primes[n];
	}

	public static void main(String[] args) {
		
		System.out.println("isPrime(6805) :: " + isPrime(6805));
		
		Scanner in = new Scanner(System.in);

		int t = in.nextInt();

		for (int i = 0; i < t; i++) {
			printPrimeSplits(in.nextInt());
		}

		in.close();
	}

	private static void printPrimeSplits(int number) {
		int split1 = 3;
		int split2 = number - 3;

		while (split1 < split2) {

			if (isPrime(split1) && isPrime(split2)) {
				System.out.println(split1 + " " + split2);
				break;
			}
			split1 += 2;
			split2 -= 2;
		}

	}

	public static void main2(String[] args) {
		// TODO Auto-generated method stub

		/*
		 * int[] test = new int[]{1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17};
		 * 
		 * for(int a: test) System.out.println(a + " :: " + isPrime(a));
		 */

		int number = 9990;
		int split1 = 3;
		int split2 = number - 3;

		while (split1 < split2) {

			if (isPrime(split1) && isPrime(split2)) {
				System.out.println(split1 + " " + split2);
				break;
			}
			split1 += 2;
			split2 -= 2;
		}

		/*
		 * boolean[] truePrimes = new boolean[10001]; truePrimes[2] = true;
		 * 
		 * for (int i = 3; i < 10000; i++) { boolean isPrime = true; int deno =
		 * (int) Math.sqrt(i); for (int j = 2; j <= deno; j++) { if (i % j == 0)
		 * { isPrime = false; break; } } if (isPrime) truePrimes[i] = true; }
		 * 
		 * for (int i = 0; i < 10001; i++) System.out.print((truePrimes[i]) +
		 * ",");
		 */

	}

}
